# Site settings
title: EPM HP BLOG
email: effectivjava@163.com
description: > # this means to ignore newlines until "baseurl:"
  there is my bolg in github for EPM
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: none
github_username:  OMGgogong

# Build settings
markdown: kramdown
